### ISSUE TITLE
Problematic attribute renaming and a missing directory

### ISSUE THREAD

**Issue by zepheiryan** [sous-chefs/aptly#37]
We pulled in the 1.0 release of this cookbook to our environment and suddenly saw our aptly root directory disappear from its expected location.  It turns out renaming the Chef attribute `rootdir` to `rootDir` resulted in the default recipe changing the aptly user's home from our `rootdir` value to the cookbook default `rootDir` value, which the Chef user resource then interprets as a request to move the old home to the new home.  Until we figured that out, though, it certainly looked like this release destroyed the entire repository.

I understand this is a major release with no assurances of backwards compatibility, but this ultimately minor change has enormous and undeclared consequences.  In my experience, renaming attributes needs a really good reason - I don't see one provided here - and either transitional bits to assist the change or a big warning to users to not get tripped up on the shift.

**Comment by YpNo** [comment]
Hi @zepheiryan, 
Sorry for the late response.

Effectively, the attributes were renamed for personal reason. I think the attributes (and the cookbook in global) is more maintainable if attributes reflects the name of service's parameters. Like you say it is a major release (last update was August, 17) with a big refacto and I made efforts to enhance Readme.

However, I agree with you that I should have written I visible Warning in Readme to warn users. I will do that asap.

Regards.

**Comment by josephholsten** [comment]
@zepheiryan I'm going to close this, but I'd love to have you actively involved in the future. Could you add yourself to https://github.com/sous-chefs/terraform-github-org and help us maintain this?
