### ISSUE TITLE
The mirror resource does not have properties for all flags available to aptly mirror create, particularly architectures

### ISSUE THREAD

**Issue by jjustice6** [sous-chefs/aptly#49]
### Cookbook version
current

### Chef-client version
any

### Platform Details
Any

### Scenario:
Mirror specific architectures per specific mirrors

### Steps to Reproduce:
Look at https://github.com/sous-chefs/aptly/blob/master/resources/mirror.rb#L19-L29 and see there is no `architecture` property.

### Expected Result:
I was expecting to be able to define specific architectures for specific mirrors as not all the mirrors I was hoping to mirror have the same architectures available. For instance, http://mirrors.rit.edu/ubuntu/dists/bionic/ only has amd64 and i386, while http://repo.percona.com/apt/dists/bionic/main/ supports amd64, i386, i686, and x86_64. and http://ppa.launchpad.net/canonical-support/support-tools/ubuntu/dists/xenial/main/ supports tons of architectures.

### Actual Result:
You are stuck only setting a single set of architectures on a global level in https://github.com/sous-chefs/aptly/blob/master/attributes/default.rb#L30 , which requires you to resort to shelling out to configure any mirrors with different sets of architectures.

Aptly supports mirror-specific architectures according to https://www.aptly.info/doc/aptly/mirror/create/ .

Note that several of the other options are also missing as properties.

**Comment by Raboo** [comment]
I could probably add support for that argument unless you would like to do a PR and add it?

**Comment by jjustice6** [comment]
Either/or is fine by me.

**Comment by jjustice6** [comment]
Looks like we're also going to need `-with-udebs` as well.

**Comment by Raboo** [comment]
If you do have the time, please submit PR with the features you need.

**Comment by jjustice6** [comment]
I'll work on it this week.

**Comment by jjustice6** [comment]
I've stubbed out what I think it'll look like in https://github.com/sous-chefs/aptly/pull/50 , but I am not familiar with this cookbook's test rig yet, so it may take me a bit more time to get that all wired up correctly.

**Comment by Raboo** [comment]
Merged #50
