### ISSUE TITLE
Aptly mirror resource does not support the -ignore-signatures option

### ISSUE THREAD

**Issue by jjustice6** [sous-chefs/aptly#61]
### Cookbook version
current

### Chef-client version
any

### Platform Details
Any

### Scenario:
Aptly does not currently support non-armored detached keys (https://github.com/aptly-dev/aptly/pull/780) until 1.4.0 releases. This is an issue when trying to mirror the ubuntu cloud archive repo (https://github.com/aptly-dev/aptly/issues/773). As we are unable to verify the keys with the current production release of aptly, and even the latest nightly release that's on the repo, ignoring the signature is the only way to mirror this repo using Aptly at all today.

See: 
https://www.aptly.info/doc/aptly/mirror/create/
https://www.aptly.info/doc/aptly/mirror/update/

The above functions would need to incorporate this into the cookbook to make it work properly - some experimentation shows that simply doing `aptly mirror create` with `-ignore-signatures` and then trying to do `aptly mirror update` results in the update attempting to verify the signature anwyay.

### Steps to Reproduce:
Look at https://github.com/sous-chefs/aptly/blob/master/resources/mirror.rb#L19-L32 and see there is no `ignore_signatures` property.

### Expected Result:
Ability to ignore the signatures and use the repo anyway.

### Actual Result:
Unable to do so using this cookbook.

**Comment by jjustice6** [comment]
(This is similar to #49 , and like that one, I'm perfectly willing to do the lifting and send in a PR for it myself, assuming everyone's fine with adding this option in.)

**Comment by Raboo** [comment]
Hi,
Sorry for the delay.

Is it only `aptly mirror create` and `aptly mirror update` that has the argument `-ignore-signatures`?

**Comment by jjustice6** [comment]
Certainly looks like it. Also `aptly mirror edit`, but this cookbook doesn't do that (yet?).

Once you have the mirror updated, you can take snapshots and publish the snapshot regardless of whether the signature was verified or not.

**Comment by Raboo** [comment]
Ok, I've started working on a PR

**Comment by freakinhippie** [comment]
This should be resolved now too with the merge of #94.

**Comment by Raboo** [comment]
@freakinhippie Great work. I totally dropped the ball on this...
